//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.9.0.
// ClassPointSystemWindow.rc

#define FIRST_RESOURCE_ID                   1000

#define IDA_MAIN_ACCEL                      501
#define IDA_EDIT_ACCEL                      502

#define IDB_TOOLBAR                         201
#define IDB_TOOLBAR_HOT                     202
#define IDB_TOOLBAR_DISABLED                203
#define IDB_SPLASH                          204
#define IDB_BACKGROUND                      205
#define IDB_BUTTON_NORMAL                   206
#define IDB_BUTTON_PRESSED                  207

#define IDD_MAIN                            301
#define IDD_ABOUT                           302
#define IDD_SETTINGS                        303
#define IDD_LOGIN                           304
#define IDD_PROGRESS                        305
#define IDD_MESSAGE                         306

#define IDI_APP_ICON                        101
#define IDI_APP_ICON_SMALL                  102
#define IDI_APP_ICON_LARGE                  103
#define IDI_DOCUMENT_ICON                   104
#define IDI_FOLDER_ICON                     105

#define IDM_FILE_NEW                        1001
#define IDM_FILE_OPEN                       1002
#define IDM_FILE_SAVE                       1003
#define IDM_FILE_SAVEAS                     1004
#define IDM_FILE_PRINT                      1005
#define IDM_FILE_EXIT                       1006
#define IDM_EDIT_UNDO                       1101
#define IDM_EDIT_REDO                       1102
#define IDM_EDIT_CUT                        1103
#define IDM_EDIT_COPY                       1104
#define IDM_EDIT_PASTE                      1105
#define IDM_EDIT_SELECTALL                  1106
#define IDM_VIEW_TOOLBAR                    1201
#define IDM_VIEW_STATUSBAR                  1202
#define IDM_VIEW_REFRESH                    1203
#define IDM_TOOLS_OPTIONS                   1301
#define IDM_TOOLS_CALC                      1302
#define IDM_HELP_CONTENTS                   1401
#define IDM_HELP_ABOUT                      1402
#define IDM_CONTEXT_COPY                    1501
#define IDM_CONTEXT_DELETE                  1502
#define IDM_CONTEXT_PROPERTIES              1503

#define IDR_MAIN_MENU                       401
#define IDR_CONTEXT_MENU                    402
#define IDR_POPUP_MENU                      403
#define IDR_VS_VERSION_INFO                 600
#define IDR_MAIN_TOOLBAR                    701
#define IDR_STANDARD_TOOLBAR                702
#define IDR_MAIN_STATUS                     801
#define IDR_HTML_HELP                       901
#define IDR_HTML_ABOUT                      902
#define IDR_CONFIG_FILE                     1001
#define IDR_LICENSE_TEXT                    1002
#define IDR_TEMPLATE_FILE                   1003

#define IDS_APP_TITLE                       2001
#define IDS_COPYRIGHT                       2002
#define IDS_COMPANY                         2003
#define IDS_OK                              2101
#define IDS_CANCEL                          2102
#define IDS_YES                             2103
#define IDS_NO                              2104
#define IDS_CLOSE                           2105
#define IDS_FILE_NEW_TIP                    2201
#define IDS_FILE_OPEN_TIP                   2202
#define IDS_ERROR_FILE_NOT_FOUND            2301
#define IDS_ERROR_ACCESS_DENIED             2302
#define IDS_ERROR_DISK_FULL                 2303
#define IDS_CONFIRM_EXIT                    2401
#define IDS_CONFIRM_DELETE                  2402

#define LAST_RESOURCE_ID                    5000

#define VS_VERSION_INFO                     1

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    1004
        #define _APS_NEXT_COMMAND_VALUE     1504
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
